---
- name: Adicionar máquina Debian ao Active Directory
  hosts: debian
  become: true
  
  vars:
    domain_name: "cedae.corp"
    realm: "CEDAE.CORP"

  vars_prompt:
    - name: domain_user
      prompt: Entre com o usuário do domínio 
      private: false
    
    - name: domain_pass
      prompt: Entre com a senha

  tasks:
    - name: Instalar pacotes necessários
      apt:
        name:
          - realmd
          - sssd
          - sssd-ad          
          - sssd-tools
          - adcli
          - krb5-user
          - packagekit
          - samba-common-bin
        state: present        

    - name: Configurar Kerberos
      ansible.builtin.copy:
        src: files/krb5.conf
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: "0644"        

    - name: Adicionar máquina ao domínio
      shell: "echo {{ domain_pass }} | realm join --verbose {{ domain_name }} -U {{ domain_user }}"
      register: realm_join
      notify: reboot

    - name: Mostra o resultado do Ingresso ao Dominio
      ansible.builtin.debug:
        var: realm_join 

    - name: Configurar SSSD
      copy:
        src: files/sssd.conf
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: "0600"
      notify:
      - restart sssd

    - name: Configurar diretorio Padrao
      lineinfile:
        path: "/etc/pam.d/common-session"
        line: "session optional        pam_mkhomedir.so skel=/etc/skel umask=077"

  handlers:
    - name: restart sssd
      systemd:
        name: sssd
        state: restarted
    - name: reboot
      reboot:
